import React from "react";
import{useEffect,useMemo,useState}from'react';import{useParams,useNavigate}from'react-router-dom';import api from'../api';import{imageUrl}from'../utils/media';
export default function BookingPage(){
  const{id}=useParams();const nav=useNavigate();const[room,setRoom]=useState(null);const[shot,setShot]=useState(null);
  const today = useMemo(()=>new Date().toISOString().split('T')[0],[]);
  const[form,setForm]=useState({checkIn:'',checkOut:'',guests:1,roomsCount:1,paymentMethod:'cash',foodRequired:false,foodItems:'',specialRequest:''});
  useEffect(()=>{api.get('/rooms/'+id).then(r=>setRoom(r.data))},[id]);
  if(!room)return <p className="p-8">Loading...</p>;
  const nights=form.checkIn&&form.checkOut?Math.max(1,Math.ceil((new Date(form.checkOut)-new Date(form.checkIn))/(1000*60*60*24))||1):1;const total=nights*Number(room.price||0)*Number(form.roomsCount||1);
  const setCheckIn=(value)=>{ setForm(prev=>({ ...prev, checkIn:value, checkOut: prev.checkOut && prev.checkOut < value ? '' : prev.checkOut })); };
  const submit=async(e)=>{e.preventDefault();try{const fd=new FormData();Object.entries({...form,roomId:id}).forEach(([k,v])=>fd.append(k,v));if(shot)fd.append('paymentScreenshot',shot);await api.post('/bookings',fd);alert('Your booking request has been sent to the owner.');nav('/my-bookings')}catch(e){alert(e.response?.data?.message||'Booking error')}};
  return <div className="max-w-5xl mx-auto p-4 md:p-6 mt-4 md:mt-8">
    <button type="button" onClick={()=>nav(-1)} className="mb-4 inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white border border-gray-200 hover:bg-gray-50 font-semibold shadow-sm">← Back</button>
    <div className="bg-white shadow rounded-[2rem] overflow-hidden border border-gray-100"><img src={imageUrl(room.images?.[0])} className="h-64 md:h-80 w-full object-cover"/><div className="p-6"><p className="text-blue-600 font-bold">Complete your booking</p><h1 className="text-3xl md:text-4xl font-black mt-1">{room.title}</h1><p className="text-gray-600 mt-1">{room.propertyName} • {room.city}</p><p className="text-blue-600 font-black text-2xl mt-3">₹{room.price}<span className="text-sm text-gray-500 font-semibold"> /night</span></p></div></div>
    <form onSubmit={submit} className="bg-white shadow rounded-[2rem] p-5 md:p-7 mt-6 grid gap-5 border border-gray-100">
      <div className="grid md:grid-cols-2 gap-4"><label className="font-semibold">Check-in Date<input required type="date" min={today} value={form.checkIn} className="border border-gray-200 p-3 rounded-2xl w-full mt-2 outline-none focus:ring-4 focus:ring-blue-100" onChange={e=>setCheckIn(e.target.value)}/></label><label className="font-semibold">Check-out Date<input required type="date" min={form.checkIn || today} value={form.checkOut} className="border border-gray-200 p-3 rounded-2xl w-full mt-2 outline-none focus:ring-4 focus:ring-blue-100" onChange={e=>setForm({...form,checkOut:e.target.value})}/></label></div>
      <div className="grid md:grid-cols-2 gap-4"><label className="font-semibold">Guests<input type="number" min="1" className="border border-gray-200 p-3 rounded-2xl w-full mt-2" value={form.guests} onChange={e=>setForm({...form,guests:e.target.value})}/></label><label className="font-semibold">Rooms Required<input type="number" min="1" className="border border-gray-200 p-3 rounded-2xl w-full mt-2" value={form.roomsCount} onChange={e=>setForm({...form,roomsCount:e.target.value})}/></label></div>
      <label className="flex gap-3 items-center font-semibold bg-gray-50 rounded-2xl p-4"><input type="checkbox" checked={form.foodRequired} onChange={e=>setForm({...form,foodRequired:e.target.checked})}/> Food required?</label>
      {form.foodRequired&&<input className="border border-gray-200 p-3 rounded-2xl" placeholder="Food items: breakfast, lunch, dinner, tea etc." value={form.foodItems} onChange={e=>setForm({...form,foodItems:e.target.value})}/>}<textarea className="border border-gray-200 p-3 rounded-2xl min-h-28" placeholder="Special request optional" value={form.specialRequest} onChange={e=>setForm({...form,specialRequest:e.target.value})}/>
      <select className="border border-gray-200 p-3 rounded-2xl" value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option value="cash">Cash on Hotel</option><option value="online">Online QR/UPI Payment</option></select>
      {form.paymentMethod==='online'&&<div className="bg-blue-50 p-5 rounded-3xl border border-blue-100"><p className="font-bold">Scan QR / Pay UPI</p>{room.owner?.qrImage?<img className="h-48 mt-3 rounded-2xl border bg-white" src={imageUrl(room.owner.qrImage)}/>:<p>Owner QR not uploaded</p>}<p className="mt-2">UPI ID: <b>{room.owner?.upiId || 'Not available'}</b></p><label className="block mt-3 font-semibold">Upload payment screenshot<input type="file" accept="image/*" onChange={e=>setShot(e.target.files[0])} className="block mt-2 text-sm"/></label></div>}
      <div className="bg-gray-50 p-5 rounded-3xl border border-gray-100"><p>Nights: {nights}</p><p>Rooms: {form.roomsCount}</p><p className="text-3xl font-black mt-2">Total: ₹{total}</p></div>
      <div className="grid sm:grid-cols-2 gap-3"><button type="button" onClick={()=>nav(-1)} className="border border-gray-200 p-4 rounded-2xl font-bold hover:bg-gray-50">Back</button><button className="bg-green-600 hover:bg-green-700 text-white p-4 rounded-2xl font-bold shadow-lg">Confirm Booking</button></div>
    </form>
  </div>
}
